export interface DayContent {
  day: number;
  week: number;
  title: string;
  description: string;
  activities: string[];
  videoUrl?: string;
  focus: string;
}

export const DAYS_DATA: DayContent[] = [
  {
    day: 1,
    week: 1,
    title: "Foundation: Top 100 Words",
    description: "Master the 100 most common English words that make up 50% of all spoken English.",
    activities: [
      "Learn 20 high-frequency pronouns and verbs",
      "Practice pronunciation with shadowing",
      "Create flashcards for daily review",
      "Narrate 3 daily actions in English",
    ],
    videoUrl: "https://www.youtube.com/embed/OP5YABLFy7s",
    focus: "Pronouns (I, you, we, they) & Essential Verbs (is, are, have, do, go)",
  },
  {
    day: 2,
    week: 1,
    title: "Structural Connectors",
    description: "Learn the connecting words that hold sentences together.",
    activities: [
      "Study 15 structural connectors (and, but, because, with)",
      "Build simple sentences using connectors",
      "Listen to native speakers using these words",
      "Write 5 sentences with each connector",
    ],
    videoUrl: "https://www.youtube.com/embed/hWYiI4euoDM",
    focus: "Connectors: and, but, because, with, or, if, when",
  },
  {
    day: 3,
    week: 1,
    title: "Present Simple Tense",
    description: "Master the most frequently used tense in English conversation.",
    activities: [
      "Learn Present Simple formation and usage",
      "Practice with 20 common verbs",
      "Create affirmative, negative, and question sentences",
      "Shadowing exercise: 10 minutes of native speech",
    ],
    videoUrl: "https://www.youtube.com/embed/ZG_OtQD2XuY",
    focus: "Present Simple: I walk, you go, she likes",
  },
  {
    day: 4,
    week: 1,
    title: "Past Simple Tense",
    description: "Learn to talk about completed actions and past events.",
    activities: [
      "Study irregular and regular past tense verbs",
      "Practice 25 common past tense forms",
      "Tell 5 simple stories about your day",
      "Listen to past tense in context",
    ],
    videoUrl: "https://www.youtube.com/embed/hWYiI4euoDM",
    focus: "Past Simple: I walked, you went, she liked",
  },
  {
    day: 5,
    week: 1,
    title: "Future Simple Tense",
    description: "Express plans, predictions, and future intentions.",
    activities: [
      "Learn 'will' and 'going to' structures",
      "Practice 20 future tense sentences",
      "Discuss your plans for the week",
      "Shadowing: Future tense expressions",
    ],
    videoUrl: "https://www.youtube.com/embed/ZG_OtQD2XuY",
    focus: "Future Simple: I will walk, you're going to go",
  },
  {
    day: 6,
    week: 1,
    title: "Subject-Verb-Object Sentences",
    description: "Build simple, clear sentences with proper structure.",
    activities: [
      "Master SVO sentence construction",
      "Create 30 simple sentences",
      "Practice with different subjects and objects",
      "Speak 10 SVO sentences aloud",
    ],
    videoUrl: "https://www.youtube.com/embed/hWYiI4euoDM",
    focus: "SVO: I want coffee. She likes music.",
  },
  {
    day: 7,
    week: 1,
    title: "Week 1 Review & Consolidation",
    description: "Review all Week 1 content and practice integrated skills.",
    activities: [
      "Review all 100 high-frequency words",
      "Practice all three tenses in context",
      "Record yourself speaking for 5 minutes",
      "Complete a comprehension quiz",
    ],
    videoUrl: "https://www.youtube.com/embed/OP5YABLFy7s",
    focus: "Integration: Combine all Week 1 concepts",
  },
  {
    day: 8,
    week: 2,
    title: "Functional Phrases: Introductions",
    description: "Master essential phrases for meeting and greeting.",
    activities: [
      "Learn 15 greeting and introduction phrases",
      "Practice: 'Where is...?', 'How are you?'",
      "Role-play introductions",
      "Shadowing: Native speaker introductions",
    ],
    videoUrl: "https://www.youtube.com/embed/hWYiI4euoDM",
    focus: "Phrases: 'Hello, my name is...', 'Nice to meet you'",
  },
  {
    day: 9,
    week: 2,
    title: "Functional Phrases: Requests & Questions",
    description: "Learn how to ask for things and get information.",
    activities: [
      "Master 'Where is...?', 'How do I...?', 'Can I...?'",
      "Practice polite request phrases",
      "Create 20 question sentences",
      "Shadowing: Question intonation",
    ],
    videoUrl: "https://www.youtube.com/embed/ZG_OtQD2XuY",
    focus: "Phrases: 'Where is...?', 'How do I...?', 'I would like...'",
  },
  {
    day: 10,
    week: 2,
    title: "Functional Phrases: Daily Conversations",
    description: "Learn phrases for everyday interactions.",
    activities: [
      "Study 20 common daily conversation phrases",
      "Practice ordering food, asking for directions",
      "Role-play common scenarios",
      "Shadowing: Conversational speech",
    ],
    videoUrl: "https://www.youtube.com/embed/hWYiI4euoDM",
    focus: "Phrases: 'What time is it?', 'How much?', 'Thank you'",
  },
  {
    day: 11,
    week: 2,
    title: "Shadowing Technique Mastery",
    description: "Perfect your shadowing technique for fluency.",
    activities: [
      "15 minutes of scripted shadowing",
      "10 minutes of audio-only shadowing",
      "Record and compare your output",
      "Focus on rhythm and intonation",
    ],
    videoUrl: "https://www.youtube.com/embed/OP5YABLFy7s",
    focus: "Shadowing: Mimic rhythm, speed, and accent",
  },
  {
    day: 12,
    week: 2,
    title: "Contextual Vocabulary: Food & Dining",
    description: "Learn vocabulary for food and restaurant situations.",
    activities: [
      "Learn 30 food-related vocabulary words",
      "Practice ordering at a restaurant",
      "Describe your favorite foods",
      "Shadowing: Restaurant dialogues",
    ],
    videoUrl: "https://www.youtube.com/embed/hWYiI4euoDM",
    focus: "Vocabulary: Food, drinks, dining phrases",
  },
  {
    day: 13,
    week: 2,
    title: "Contextual Vocabulary: Work & Technology",
    description: "Learn professional and tech-related vocabulary.",
    activities: [
      "Learn 30 workplace vocabulary words",
      "Practice tech-related conversations",
      "Describe your job or field",
      "Shadowing: Professional dialogues",
    ],
    videoUrl: "https://www.youtube.com/embed/ZG_OtQD2XuY",
    focus: "Vocabulary: Work, tech, professional terms",
  },
  {
    day: 14,
    week: 2,
    title: "Week 2 Review & Real-Time Output",
    description: "Review Week 2 and begin real-time speaking practice.",
    activities: [
      "Review all functional phrases",
      "Practice with AI voice partner (simulated)",
      "Record 5-minute conversation",
      "Evaluate your progress",
    ],
    videoUrl: "https://www.youtube.com/embed/OP5YABLFy7s",
    focus: "Integration: Functional phrases + real output",
  },
  {
    day: 15,
    week: 3,
    title: "Micro-Immersion: Phone Setup",
    description: "Create your micro-immersion bubble.",
    activities: [
      "Change phone OS language to English",
      "Install English learning apps",
      "Set up English notifications",
      "Watch 20 minutes of English media with subtitles",
    ],
    videoUrl: "https://www.youtube.com/embed/hWYiI4euoDM",
    focus: "Immersion: Change device settings to English",
  },
  {
    day: 16,
    week: 3,
    title: "Micro-Immersion: Media Consumption",
    description: "Immerse yourself in English content.",
    activities: [
      "Watch 30 minutes of English video with English subtitles",
      "Choose content at your level (children's shows, podcasts)",
      "Take notes on new words",
      "Narrate 10 minutes of your daily actions aloud",
    ],
    videoUrl: "https://www.youtube.com/embed/ZG_OtQD2XuY",
    focus: "Immersion: English audio + English subtitles",
  },
  {
    day: 17,
    week: 3,
    title: "Real-Time Output: Speaking Practice",
    description: "Start speaking with real people or AI partners.",
    activities: [
      "30-minute conversation practice (AI or language partner)",
      "Focus on expressing ideas, not perfection",
      "Record and review your speech",
      "Identify areas for improvement",
    ],
    videoUrl: "https://www.youtube.com/embed/OP5YABLFy7s",
    focus: "Output: Speak, make mistakes, learn",
  },
  {
    day: 18,
    week: 3,
    title: "Real-Time Output: Confidence Building",
    description: "Build confidence through consistent speaking.",
    activities: [
      "30-minute conversation practice",
      "Try new topics and vocabulary",
      "Ask for corrections and feedback",
      "Celebrate small wins",
    ],
    videoUrl: "https://www.youtube.com/embed/hWYiI4euoDM",
    focus: "Output: Build fluency through repetition",
  },
  {
    day: 19,
    week: 3,
    title: "Consistency Check: Daily Routine",
    description: "Establish a sustainable daily learning routine.",
    activities: [
      "20 minutes: Shadowing practice",
      "15 minutes: Vocabulary review",
      "20 minutes: Speaking practice",
      "Reflect on your progress",
    ],
    videoUrl: "https://www.youtube.com/embed/ZG_OtQD2XuY",
    focus: "Consistency: 20 minutes daily beats 4 hours once",
  },
  {
    day: 20,
    week: 3,
    title: "Advanced Phrases: Opinions & Preferences",
    description: "Express your thoughts and preferences.",
    activities: [
      "Learn 20 opinion and preference phrases",
      "Practice: 'I think...', 'I prefer...', 'I like...'",
      "Discuss your opinions on various topics",
      "Shadowing: Opinion expressions",
    ],
    videoUrl: "https://www.youtube.com/embed/OP5YABLFy7s",
    focus: "Phrases: 'I think...', 'I prefer...', 'I believe...'",
  },
  {
    day: 21,
    week: 3,
    title: "Week 3 Review & Integration",
    description: "Review all three weeks and integrate all skills.",
    activities: [
      "Review vocabulary from all three weeks",
      "Practice all three tenses in context",
      "30-minute conversation practice",
      "Evaluate overall progress",
    ],
    videoUrl: "https://www.youtube.com/embed/hWYiI4euoDM",
    focus: "Integration: Combine all skills learned",
  },
  {
    day: 22,
    week: 4,
    title: "Listening Comprehension: Unscripted Speech",
    description: "Train your ear for natural, unscripted English.",
    activities: [
      "Listen to unscripted YouTube videos (5 minutes)",
      "Identify familiar words and phrases",
      "Watch with English subtitles",
      "Repeat key phrases",
    ],
    videoUrl: "https://www.youtube.com/embed/ZG_OtQD2XuY",
    focus: "Listening: Unscripted, natural speech",
  },
  {
    day: 23,
    week: 4,
    title: "Listening Comprehension: Podcasts & Audiobooks",
    description: "Expand listening to diverse content.",
    activities: [
      "Listen to English podcast (15 minutes)",
      "Choose beginner-friendly content",
      "Take notes on new vocabulary",
      "Repeat difficult phrases",
    ],
    videoUrl: "https://www.youtube.com/embed/OP5YABLFy7s",
    focus: "Listening: Podcasts, audiobooks, natural speech",
  },
  {
    day: 24,
    week: 4,
    title: "Speaking Fluency: Storytelling",
    description: "Practice speaking through storytelling.",
    activities: [
      "Tell a 5-minute story about your day",
      "Use all three tenses naturally",
      "Record and review your speech",
      "Identify areas for improvement",
    ],
    videoUrl: "https://www.youtube.com/embed/hWYiI4euoDM",
    focus: "Speaking: Tell stories naturally",
  },
  {
    day: 25,
    week: 4,
    title: "Speaking Fluency: Debates & Discussions",
    description: "Engage in more complex conversations.",
    activities: [
      "Discuss a topic with a language partner",
      "Express and defend your opinions",
      "Ask follow-up questions",
      "Record and analyze your speech",
    ],
    videoUrl: "https://www.youtube.com/embed/ZG_OtQD2XuY",
    focus: "Speaking: Debate, discuss, express opinions",
  },
  {
    day: 26,
    week: 4,
    title: "Vocabulary Expansion: Advanced Topics",
    description: "Learn vocabulary for more complex topics.",
    activities: [
      "Learn 30 new vocabulary words on a topic of interest",
      "Read simple articles on that topic",
      "Discuss the topic in conversation",
      "Create a personal vocabulary list",
    ],
    videoUrl: "https://www.youtube.com/embed/OP5YABLFy7s",
    focus: "Vocabulary: Topic-based, contextual learning",
  },
  {
    day: 27,
    week: 4,
    title: "Grammar in Context: Complex Sentences",
    description: "Learn to form more complex sentences.",
    activities: [
      "Study conditional sentences (if...then)",
      "Learn relative clauses (who, which, that)",
      "Practice in conversation",
      "Write 10 complex sentences",
    ],
    videoUrl: "https://www.youtube.com/embed/hWYiI4euoDM",
    focus: "Grammar: Conditionals, relative clauses",
  },
  {
    day: 28,
    week: 4,
    title: "Pronunciation & Accent Training",
    description: "Refine your pronunciation and accent.",
    activities: [
      "Focus on difficult English sounds",
      "Shadowing: 20 minutes on pronunciation",
      "Record and compare with native speaker",
      "Practice word stress and intonation",
    ],
    videoUrl: "https://www.youtube.com/embed/ZG_OtQD2XuY",
    focus: "Pronunciation: Sounds, stress, intonation",
  },
  {
    day: 29,
    week: 4,
    title: "Comprehensive Review & Assessment",
    description: "Review all 30 days of learning.",
    activities: [
      "Complete a comprehensive vocabulary test",
      "Record a 10-minute conversation",
      "Evaluate your progress across all areas",
      "Identify remaining challenges",
    ],
    videoUrl: "https://www.youtube.com/embed/OP5YABLFy7s",
    focus: "Review: Assess all skills learned",
  },
  {
    day: 30,
    week: 4,
    title: "Celebration & Next Steps",
    description: "Celebrate your progress and plan your future learning.",
    activities: [
      "Reflect on your 30-day journey",
      "Record a final 5-minute speech",
      "Plan your next learning phase",
      "Set new goals for continued growth",
    ],
    videoUrl: "https://www.youtube.com/embed/hWYiI4euoDM",
    focus: "Celebration: You've built a foundation!",
  },
];

export default DAYS_DATA;
